; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.17"

; Modules
projects[backup_migrate][version] = "2.4"

projects[ctools][version] = "1.2"

projects[date][version] = "2.0-rc1"

projects[email][version] = "1.2"

projects[i18n][version] = "1.7"

projects[invisimail][version] = "1.1"

projects[libraries][version] = "2.0"

projects[link][version] = "1.0"

projects[references][version] = "2.0"

projects[panels][version] = "3.0-alpha3"

projects[variable][version] = "1.2"

projects[views][version] = "3.5"

projects[views_slideshow][version] = "3.0"

projects[wysiwyg][version] = "2.2"

; projects[admin_menu][version] = "2.2" ;check version

; Themes
projects[bluemasters][version] = "1.3"

projects[science_gordon][version] = "1.7"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[metatag_twittercard][download][type] = ""
projects[metatag_twittercard][download][url] = ""
projects[metatag_twittercard][type] = "module"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tinymce][download][type] = ""
libraries[tinymce][download][url] = ""
libraries[tinymce][directory_name] = "tinymce"
libraries[tinymce][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[jquery.cycle][download][type] = ""
libraries[jquery.cycle][download][url] = ""
libraries[jquery.cycle][directory_name] = "jquery.cycle"
libraries[jquery.cycle][type] = "library"

